# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Darron Froese
tagline:          ''
description:      'System administration, tricks and tips from an old school web-hacker.'
url:              http://blog.froese.org

author:
  name:           'Darron Froese'
  url:            https://twitter.com/darron

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/darron

exclude:          ['vendor']